### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by edewit**
@corinnekrych removed hello world from template and updated license and Readme

### CODE REVIEW

**Comment by corinnekrych** [comment]
@edewit When trying to run it on iOS, it seems it doesn't find the reference to shared code

```
/Users/corinne/src/fheng/saml-xamarin-app/saml-xamarin-app/saml-ios-app/AppDelegate.cs(31,31): Error CS0234: The type or namespace name `Shared' does not exist in the namespace `Helloworld_XamarinForms'. Are you missing an assembly reference? (CS0234) (saml-ios-app)
```

**Comment by corinnekrych** [comment]
@secondsun do you face the same issue?

**Comment by secondsun** [comment]
@corinnekrych I haven't tried.  All I know is the Android push starter isn't compiling because of a similar issue.  Maybe it is related to my 1.3.7.Release PR? (https://github.com/feedhenry/fh-dotnet-sdk/pull/48)

**Comment by corinnekrych** [comment]
@secondsun in this version we use 1.3.6 release
1.3.7 contains sync fixes

**Comment by secondsun** [comment]
@corinnekrych I can't clone the master project correctly because the paths are too long for windows to handle ><

**Comment by edewit** [comment]
@corinnekrych @secondsun updated the packages and added the references, don't know what happened to the project files

**Comment by corinnekrych** [comment]
@edewit this Pr fixes build issue and remove some unused code
+1 to merge
I was not able to test runtime yet (saml idp not started) but we can merge this one

**Pull request merged**
